services:
  - type: web
    name: goldprofx
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: MM_TELEGRAM_BOT_TOKEN
        sync: false
      - key: MM_TELEGRAM_CHAT_ID
        sync: false
